name: lint_hard
version: 1.0.3
homepage: https://github.com/noojee/lint_hard.git
description: All the lints except where they clash.
repository: https://github.com/noojee/lint_hard.git
environment: 
  sdk: '>=2.12.0 <3.0.0'
