name: lint_hard
version: 3.0.0-beta.1
homepage: https://github.com/noojee/lint_hard.git
description: All the lints except where they clash.
repository: https://github.com/noojee/lint_hard.git
environment: 
  sdk: '>=2.19.0-444.2.beta <3.0.0'
